spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:33061/loa_bot?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: test1234 # ????? ??? ??? ?? (?: 1234), ??? ???

  jpa:
    hibernate:
      ddl-auto: update  # ?? ????? Entity ?? ? ??? ?? ????
    show-sql: true      # ???? SQL? ??? ??? (??? ??)
    properties:
      hibernate:
        format_sql: true # SQL? ??? ???? ???

  batch:
    jdbc:
      initialize-schema: always # ??? ?? ??? ??? ?? ??? ?? ??
    job:
      enabled: false # ?? ? ??? ??? ?? ???? ? ?? (??? ?? ?? ??)

logging:
  level:
    org.hibernate.SQL: debug # SQL ?? ?? ??


lostark:
  api:
    url: https://developer-lostark.game.onstove.com/markets/items
    key: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IktYMk40TkRDSTJ5NTA5NWpjTWk5TllqY2lyZyIsImtpZCI6IktYMk40TkRDSTJ5NTA5NWpjTWk5TllqY2lyZyJ9.eyJpc3MiOiJodHRwczovL2x1ZHkuZ2FtZS5vbnN0b3ZlLmNvbSIsImF1ZCI6Imh0dHBzOi8vbHVkeS5nYW1lLm9uc3RvdmUuY29tL3Jlc291cmNlcyIsImNsaWVudF9pZCI6IjEwMDAwMDAwMDAwMzkyNDUifQ.RBx266OdTa1IAazb-RAn2izLe6buAsm1Elp6r3ftGxpsp7ZhcxAp1DSZkr3Eqn3-unYb52IfPKeT92aMwWib_Nfo9xiVHFzVizIjXxT7G0B82GLrrd-iHnFQo3dY3yQZ1C54YyR0ti1QhNywoCotVuTc5yqCQ-00G5GshMGFfaIRAoHl_JguJG-4qL3Hq4vzQW5Y6shXzzT6HB4YGd66ZrEtZztrIqmWkG1i2r1n93X4ri1RpMAlocGNixN6tSAUNAznUUG8_CWI_ryz_x1XNxbIYI-rzOmxXGTsrztLZt8V3vHELO0XQPpRygygDDa37GjBGHNW777HzqfY7yz55g